version: '3.8'

services:
  wiremock:
    image: wiremock/wiremock:2.35.0
    ports:
      - "8081:8080"
    volumes:
      - ./src/test/wiremock/mappings:/home/wiremock/mappings
    command: ["--verbose"]